### ISSUE TITLE
Add ncdf4?

### ISSUE THREAD

**Issue by dlebauer** [rocker-org/geospatial#10]
The ncdf4 package was available in previous releases (through 3.3.3 https://github.com/rocker-org/geospatial/search?utf8=%E2%9C%93&q=ncdf4&type=) and then appears to have been removed. There have been a lot of modifications so I wanted to check if this was intentionally removed from the geospatial container, or if it just got lost. 

If it wasn't intentionally removed, could you please re-add it?

**Comment by cboettig** [comment]
Thanks for the heads up -- that does look like an oversight and we should probably add `ncdf4` back.  Though while we're on the topic, netcdf and hdf5 support in R seem to be a bit of a moving target, I'm actually still trying to wrap my head around which packages provide the most robust & consistent treatment of these datatypes. 

For instance, I understand `sf` supports netcdf `nc` files (not sure if that's ncdf3 or 4 or both) via GDAL -- how does that compare to the utilities in the `ncdf4` package?  

Would also welcome input/clarification on recommended choices here from others! cc @edzer @mdsumner / anyone else.  Does `ncdf4` provide features not accessible via GDAL wrappers in `sf` or `rgdal`?  Also, should we consider adding a package for more generic `hdf5` support here ([probably `hdf5r`](https://hhoeflin.github.io/hdf5r/articles/hdf5r.html))?  

(Would love to see `hdf5` as a drop-in replacement for `.RData` one day, I'm envious that Matlab's `.mat` files are valid `hdf5` binaries.)

**Comment by eddelbuettel** [comment]
The [h5](https://cran.r-project.org/package=h5) package seems to be current and maintained but I don't really use hdf5 data sets...

**Comment by cboettig** [comment]
Yup, though looks like the h5 README marks it as deprecated in favor of hdf5r: https://github.com/mannau/h5#deprecation-notice

**Comment by eddelbuettel** [comment]
Ah, was unaware of that last iteration.

**Comment by mdsumner** [comment]
@cboettig yes, ncdf4 provides a lot that rgdal and sf cannot provide - both provide access via GDAL which has a subset of models expressible in NetCDF, and sf can only read the vector interpretations. 

There is no good single-approach and IMO both ncdf4 and RNetCDF are generic and important enough to support. I've also written about the landscape here: 

https://github.com/r-spatial/discuss/issues/14#issuecomment-317145630
https://github.com/RConsortium/wishlist/issues/3

The relevant and *limited by the GDAL data model* drivers are NetCDF (raster and vector), GMT, and HDF5, and the DODS wrappers: 

raster: 
http://gdal.org/frmt_netcdf.html
http://gdal.org/frmt_various.html#GMT
http://gdal.org/frmt_hdf5.html
http://gdal.org/frmt_dods.html

vector:
http://gdal.org/frmt_netcdf_vector.html
http://gdal.org/drv_dods.html

(There may be others, I only list these to confirm that it is a *complex and moving target* as you say, with implications in many places. RNetCDF is more active than ncdf4, and now supports OpenDAP on Windows CRAN, ncdf4 is integral to using the raster package).

**Comment by dlebauer** [comment]
At the risk of overloading the package ... I also find the command line program ncdump, which is provided by netcdf-bin, to be very handy - especially now that Rstudio provides a terminal.


I use it to view file metatdata: `ncdump -h myfile.nc` is equivalent to `print(ncdf4::nc_open(myfile.nc))`

This is the first time I've found it missing from a server that supports using netcdf ... I suspect this may be related to the use of `--no-install-recommends` so I am recommending explicit installation 😄

**Comment by cboettig** [comment]
Thanks @mdsumner , this is just what I was hoping to hear about!  Super helpful.  

At this point it sounds like we'd want `ncdf4` and `RNetCDF` then in `rocker/geospatial`, though it also sounds as if both leave something to be desired in terms of design issues.  Curious what you think of the approach being taken in hdf5r package; seems to be going in the right direction with nearly feature-complete 1:1 bindings to the hdf5 and plans for a dplyr-based interface, which would be nice.  I gather the current netcdf is already based on hdf5 but it probably makes sense to stick with direct bindings to the standard netcdf library a la RNetCDF?  In any event, I'll be watching https://github.com/r-spatial/discuss/issues/14#issuecomment-317145630 now!

**Comment by dlebauer** [comment]
Thanks for the quick fix @cboettig!

**Comment by cboettig** [comment]
np, @dlebauer thanks for catching this and to you and Michael for the detailed feedback!
