### ISSUE TITLE
Failing builds on versioned images

### ISSUE THREAD

**Issue by dlebauer** [rocker-org/geospatial#11]
These are failing in the geospatial container: 

https://hub.docker.com/r/rocker/geospatial/builds/

![image](https://user-images.githubusercontent.com/464871/36989690-0925eac4-2068-11e8-840e-fac0d29c89f7.png)

But not in the parent rocker/verse https://hub.docker.com/r/rocker/verse/builds/ builds that were done on the same day. Perhaps the geospatial builds just need to be re-launched?

**Comment by cboettig** [comment]
yeah, looks like random Docker Hub failures, I'll relaunch them and see how that goes.  (stable tags are rebuilt at the start of each month)

**Comment by cboettig** [comment]
Rebuilds successfully completed.
