### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by Robinlovelace** [rocker-org/geospatial#13]
Heads-up @cboettig I noticed just now the build is failing on docker: https://hub.docker.com/r/rocker/geospatial/builds/

My geocompr [docker build](https://hub.docker.com/r/robinlovelace/geocompr/builds/bpbxf3bwyxawsnotcjx7wb/) which builds FROM rocker/geospatial is also failing FYI - noticed a few weeks ago but though it worth leaving a while before looking-into the issue. Not sure how to fix it but suspect this may be something to do with the solution: https://github.com/r-spatial/sf/commit/34f655a79cd73a6ddcc3b5dcc6f19e2544940016#diff-354f30a63fb0907d4ad57269548329e3

**Comment by cboettig** [comment]
Thanks @Robinlovelace for the ping!  (Also realized I didn't restart my cron tasks after our server upgrade so it's been a few weeks with no nightly builds).  

I think the underlying error is still this issue in `rgeos` config which [I posted on r-sig-geo](http://r-sig-geo.2731867.n2.nabble.com/Re-Unexpected-configure-error-following-recent-rgeos-release-td7592423.html).  Sounds like Roger already resolved it upstream on r-forge, I was hoping we'd see a new CRAN release soon but so far seems `rgeos` is still at `0.4-1`...  

I can try bumping the Dockerfile to use the r-forge version for `rgeos` until then...

**Comment by Robinlovelace** [comment]
Aha makes sense, I saw some **rgeos** questions on r-sig-geo. Another ping may help help here: @rsbivand thanks for fixing **rgeos** upstream, any ideas on an ETA for the latest version being on CRAN? But yes, looks like the interim solution is to install that pkg with:

```r
install.packages("rgeos", repos="http://R-Forge.R-project.org"))
```

Useful to know there's a fix but I'd be inclined to wait if a CRAN update is imminent (there may be more GEOS 'chaos' and other factors I don't know about delaying a release I guess).

**Comment by eddelbuettel** [comment]
@rsbivand recommended the same to me in private mail when I pointed out that this toolchain was broken on the machine I used for Rcpp reverse dependency checks.

I do not use spatial packages much and cannot really comment on this, but leaving a CRAN package as "built-broken" strikes me as suboptimal.  Then again, all you spatial guys are experienced and you know what you are doing so I may well miss something -- but I'd push this to CRAN sooner rather than later (and again, I am fully ignorant of what side effects it may trigger at CRAN...).  

Oh the joy of a _spatial_-verse...

**Comment by rsbivand** [comment]
OK, I'll start local rev-dep checks ...

**Comment by rsbivand** [comment]
Reverse dependency checks OK. Could a debian/ubuntu user affected by the 0.4-1 issue please confirm that the current status of `install.packages("rgeos", repos="http://R-Forge.R-project.org")` installs (configure.ac unchanged, log file updated)? I'll wait before submitting to CRAN for confirmation that this version is OK.

**Comment by cboettig** [comment]
@rsbivand yes, that works fine with me testing on Debian.

**Comment by rsbivand** [comment]
OK. thanks! I'll submit.

**Comment by rsbivand** [comment]
rgeos 0.4-2 on CRAN; hope this is settled until the next sed blunder at GEOS.

**Comment by eddelbuettel** [comment]
BTW a very simple way to check on 'standard Debian' is to start with the `r-base` container.

**Comment by Robinlovelace** [comment]
Many thanks everyone.

**Comment by Robinlovelace** [comment]
Build is fixed 🍾

**Comment by cboettig** [comment]
🍾
