### ISSUE TITLE
Plans to update to python 3.6 or 3.7?

### ISSUE THREAD

**Issue by josiekre** [rocker-org/geospatial#19]
I'm using `typing` with python 3.7, but I also use a lot of geospatial tools and munging in R. I am running in circles a bit trying to get python upgraded to 3.7 on a container that has R working with geospatial tools. Hints?

**Comment by cboettig** [comment]
@josiekre thanks for filing the issue.  Short answer is that the next Debian stable release will ship with python 3.7 later this year, probably early summer.  Until then, `geospatial` is likely to remain with python 3.5.

Can you elaborate a bit more on your use case?  (I'm not familiar with `typing` and it's not a very google-able name; is it not compatible with python 3.5?)

 `geospatial` pulls in python and python3 from the Debian apt repositories.  Building against the stable releases gives us (and developers building on these images) a predictable, stable and familiar environment, but also means that outside of the R packages themselves system libraries aren't the latest (same for compilers, blas libraries etc).  These can be installed manually either on these images or often just pulled from apt-get on our `debian:testing` based stack (`r-base` and friends), so you might look there to just be able to apt-get a lot more cutting edge stuff. that approach is not so well suited for maintaining a reproducible environment that can be rebuilt from scratch to the same versions years later.  

Hope this helps.  If there's a compelling case to be made for having 3.7 available now it's something we can look into, but as you have seen this has to be done with some care to get everything to work as expected.

**Comment by josiekre** [comment]
Check out https://docs.python.org/3/library/typing.html for information on type hints. It is still in development, but the basic features do not seem to be changing.

It definitely does not fall under "stable" but is uber useful. 

Thanks for the timeline estimate.

If I'm writing my own Dockerfile from `rocker/geospatial:3.5.1`, do you know how I would install python3.6 or python3.7 to those executables so that I do not mess with any of the core python3? I think I've done it before manually on a Ubuntu machine (namely, installed Python 3.6 at python3.6), but now I cannot figure out how I did that.

**Comment by cboettig** [comment]
Looks like `typing` was introduced in 3.5, so it should be available there?  e.g.  https://docs.python.org/3.5/library/typing.html.  but I dunno.

If you want to look at adding Python 3.7, my preferred strategy for this kind of thing is to check out the official docker image, in this case, https://hub.docker.com/_/python/.  There, you'll see links to Dockerfiles building on various base images, including `debian:stretch`, which is the base image for `rocker/geospatial:3.5.1` (and all other tags between 3.4.0 and latest): https://github.com/docker-library/python/blob/3189e185470f8abd8957c78973cda6b2413ca0fe/3.7/stretch/Dockerfile

I haven't tested it but from a quick look that should make `python3` default (`/usr/local/bin/python3`) at version 3.7, and should coexist relatively comfortably with the stuff that's already on, but no promises there.  Official images are pretty good at pinning versions etc so basing your recipe on that Dockerfile should give you something that is still a reproducible build next year too (by which point `rocker/geospatial` should also be entirely on 3.7 anyway).  HTH

**Comment by josiekre** [comment]
Thanks so much! I will dig into the links you've included.
