### ISSUE TITLE
Remove build-deps after install to reduce image size

### ISSUE THREAD

**Issue by cboettig** [rocker-org/geospatial#2]
With GDAL and other tools compiled from source, we end up installing a lot of dev libraries only needed at compile time.  We can remove these after install as we do in `rocker/r-ver` to reduce image size. Obviously care must be taken to avoid removing any runtime dependencies.

**Comment by nuest** [comment]
Have you thought about multi-stage builds for this?

I have not used them myself (as I'm rarely compiling large dependencies), so I'm really wondering: [purging build-deps](https://github.com/rocker-org/rocker-versioned/blob/master/r-ver/Dockerfile#L129) like on `r-ver` could be less complex to maintain, but copying over compiled libraries could be more explicit ("this is what we need in the next step").

**Comment by cboettig** [comment]
Good question. Can docker hub handle multi stage for automated builds?

For geospatial, this issue is somewhat moot since we are now able to get gdal etc from Debian binaries, so we dropped some of the build deps already.  (Interestingly, this had little impact on image size anyway).

Guess we can close this out in light of that?

**Comment by nuest** [comment]
Docker Hub [supports multi stage builds](https://github.com/docker/hub-feedback/issues/1039#issuecomment-323761501).

**I agree this can be closed.** If  image size becomes an issue again (e.g. if builds go back to compiling from source for some reason) we can reconsider the idea.
