### ISSUE TITLE
ERROR_CONNECTION_REFUSED when trying to open Rstudio server in browser

### ISSUE THREAD

**Issue by vlandau** [rocker-org/geospatial#22]
Firstly thanks to the developers for providing these great Rstudio containers! I'm having an issue with rocker/geospatial:3.5.2 on Ubuntu 18.04. I run the docker container using the following command:
```bash
sudo docker run -it --rm \
     -v "$(pwd)":/home/files \
     -e USER=usrname \
     -e PASSWORD=pwrd \
     -p 8666:8787 \
     rocker/geospatial:3.5.2
```

When I navigate to http://localhost:8787 I'm confronted with the following error:

> localhost refused to connect Try:
>        Checking the connection
>        Checking the proxy and the firewall
>ERR_CONNECTION_REFUSED

(The same problem exists with rocker/tidyverse images as well.)

I've checked to see if the port is open after running the container using the following:
```sudo netstat -tulpn```
Here's the output: (not sure exactly how to interpret this)
>Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      859/systemd-resolve 
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      1057/cupsd          
tcp        0      0 127.0.0.1:28731         0.0.0.0:*               LISTEN      19178/rsession      
tcp        0      0 127.0.0.1:21469         0.0.0.0:*               LISTEN      19178/rsession      
tcp6       0      0 ::1:631                 :::*                    LISTEN      1057/cupsd          
tcp6       0      0 :::8666                 :::*                    LISTEN      29016/docker-proxy  
tcp6       0      0 :::4125                 :::*                    LISTEN      19178/rsession      
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           12976/chrome --type 
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           12932/chrome        
udp        0      0 224.0.0.251:5353        0.0.0.0:*                           12932/chrome        
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           1069/avahi-daemon:  
udp        0      0 0.0.0.0:56883           0.0.0.0:*                           1069/avahi-daemon:  
udp        0      0 127.0.0.53:53           0.0.0.0:*                           859/systemd-resolve 
udp        0      0 0.0.0.0:68              0.0.0.0:*                           3075/dhclient       
udp        0      0 0.0.0.0:631             0.0.0.0:*                           1152/cups-browsed   
udp6       0      0 :::5353                 :::*                                1069/avahi-daemon:  
udp6       0      0 :::34104                :::*                                1069/avahi-daemon: 

This issue does not appear when accessing other docker containers through a local port (netdata, for example). I have run rocker/geospatial successfully on this machine in the past, so I'm not sure if this has to do with some inadvertently-changed setting... I'm not running through any proxy servers or VPNs, in case that is relevant.

## Other info
docker version: 
>Docker version 18.09.4, build d14af54266

OS:
Ubuntu 18.04

These rocker images have been awesome and super useful, so I'm hoping to get back up and running as soon as I can. Thanks for any help!

**Comment by cboettig** [comment]
@vlandau maybe it was a typo, but in your example you've bound to `8666`, not `8787`.  (Recall that in the port binding syntax, `-p 8666:8787`, the left hand side is the localhost port, the right-hand side always needs to be 8787).  So if you ran the code you've pasted above, you should be going to  http://localhost:8666 instead.

**Comment by vlandau** [comment]
Well that's embarrassing...  :flushed: That was my issue! Thanks so much!

I really appreciate your quick response, and thanks again for all your awesome work on these containers.
