### ISSUE TITLE
spatialreg package support

### ISSUE THREAD

**Issue by pinehowe** [rocker-org/geospatial#23]
Spatial regression models that used to be in spdep have been moved to a new package [spatialreg](https://cran.r-project.org/web/packages/spatialreg/index.html). Could this package be included in the geospatial library please?

**Comment by cboettig** [comment]
@pinehowe Thanks for the suggestion, this sounds reasonable to me.  Want to make a PRs against both `master` and `devel` branches to add this to the Dockerfile?

**Comment by cboettig** [comment]
done in 4.x images, see #34
