### ISSUE TITLE
proj6

### ISSUE THREAD

**Issue by cboettig** [rocker-org/geospatial#30]
add support for proj6, (e.g. 6.2.1) since `buster` is shipping proj v5 (https://github.com/r-spatial/discuss/issues/28#issuecomment-551241421)

**Comment by Robinlovelace** [comment]
This question may be of use/interest: https://github.com/r-spatial/discuss/issues/35 Also just came across this: https://salsa.debian.org/debian-gis-team/proj

**Comment by cboettig** [comment]
Resolved in >= 4.0.0 images, which build on ubuntu20.04 and all have proj6 out of the box in the standard repos.

**Comment by Robinlovelace** [comment]
Great work!
