### ISSUE TITLE
Mapping linux tools to R packages

### ISSUE THREAD

**Issue by emilmahler** [rocker-org/geospatial#32]
This geospatial Docker image is awesome; I made my own before realising this existed - mine was 8GB, while this one is more like 4.5GB.

To understand this package a bit better, but also remove necessary linux tools and R packages from my own build, does there exist any documentation on how each "apt-get" package relates to each R package? Perhaps a simple mapping diagram would be useful in the Readme. I would be happy to help. I've never made such a diagram, so suggestions welcome.

![geospatial package mapping](https://user-images.githubusercontent.com/16254022/78792351-4a3e7180-79b1-11ea-8562-9747fece27cc.png)

**Comment by eddelbuettel** [comment]
_If_ a particular package is provided as a `r-cran-*` binary (e.g. from the Rutter PPA with its 4000 binaries) _then_ you of course have the full declaration of depends via the package. (And I have a package `RcppAPT` that allows to even query `apt`'s db from R.)

Else _if_ the package has a binary you can of course run `ldd` on its shared library.  That really is what `apt` and friends do.

Else you can look into Gabor's `sysreqs` (hope I spelled that right) backend db used by RHub and other projects.  It also has it.  (But I can never remember if it is at GitHub under rhub or r-lib or ... as they have too many suborgs.)

**Comment by cboettig** [comment]
Adding to Dirk's list above, RSPM will also tell you this information now, e.g. see https://packagemanager.rstudio.com/__api__/swagger/index.html.
