### ISSUE TITLE
Request: rocker/geoverse = rocker/geospatial + rocker/verse additions

### ISSUE THREAD

**Issue by noamross** [rocker-org/geospatial#4]
Happy to try my hand at a PR of this if you think its OK.

**Comment by cboettig** [comment]
Good point. Wonder if it would be best to just bump the `FROM` of the current `rocker/geospatial` up to `verse` instead of `tidyverse`, given that the `geospatial` image isn't particularly light weight to begin with that's probably simpler.  Any objections?

**Comment by nuest** [comment]
I think this is closed by https://github.com/rocker-org/geospatial/commit/1704a5df2ebcbb6392a569d2db223751e33a0ae3

**Comment by cboettig** [comment]
Yup, thanks
