### ISSUE TITLE
Add tmap

### ISSUE THREAD

**Issue by Robinlovelace** [rocker-org/geospatial#6]
A powerful pkg for visualisation.

The current version doesn't allow it to be installed - it needs `libprotobuf-dev`, `libjq-dev` and maybe a few other system dependencies to work I think. Could put in a PR for this if I get 👍 that this is a good idea...

Declaration of vested interest: I'm thinking of user rocker/geospatial as the basis of https://hub.docker.com/r/robinlovelace/geocompr/ which currently uses the larger but less frequently updated ropensci container.

**Comment by Robinlovelace** [comment]
Reprex of my attempt running on the latest version or rocker/geospatial: 

``` r
install.packages("tmap")
#> Installing package into '/usr/local/lib/R/site-library'
#> (as 'lib' is unspecified)
#> also installing the dependencies 'protolite', 'geojson', 'jqr', 'geojsonio', 'rmapshaper', 'tmaptools'
#> Warning in install.packages("tmap"): installation of package 'protolite'
#> had non-zero exit status
#> Warning in install.packages("tmap"): installation of package 'jqr' had non-
#> zero exit status
#> Warning in install.packages("tmap"): installation of package 'geojson' had
#> non-zero exit status
#> Warning in install.packages("tmap"): installation of package 'geojsonio'
#> had non-zero exit status
#> Warning in install.packages("tmap"): installation of package 'rmapshaper'
#> had non-zero exit status
#> Warning in install.packages("tmap"): installation of package 'tmaptools'
#> had non-zero exit status
#> Warning in install.packages("tmap"): installation of package 'tmap' had
#> non-zero exit status
```

**Comment by cboettig** [comment]
Hi @Robinlovelace , great suggestion, I'd welcome a PR.  Yup, I think making sure that this image has all the dependencies for geocompr book would be a nice benchmark; I'm  a big fan of the work you folks are doing there.

**Comment by Robinlovelace** [comment]
Job done it seems:

![image](https://user-images.githubusercontent.com/1825120/33603203-b5db7a46-d9a9-11e7-8c83-9fdfa09e85cb.png)


Any issues you see with this build let me know: https://hub.docker.com/r/robinlovelace/geocompr/builds/bdmus6trgzbkixaqyd9xprd/

**Comment by Robinlovelace** [comment]
Update: I just pulled down the latest version of rocker/geospatial and did

```
docker run -d -p 8787:8787 -v D:/geocompr:/data robinlovelace/geocompr
```

Happy to say the entire book built on there without issue after I ran this from inside RStudio Server:

```r
bookdown::render_book("index.Rmd") # to build the book
browseURL("_book/index.html") # to view it
```

cc @Nowosad and @Jannes-m: containerised geocompr works!
